### ISSUE TITLE
TypeError: util.isNode is not a function after upgrading to 3.3.1

### ISSUE THREAD

**Issue by onhate** [freshollie/jest-dynalite#32]
I'm getting `TypeError: util.isNode is not a function` here https://github.com/aws/aws-sdk-js/blob/54f8555bd94d33a1754a44a35286f1d9e31c28a3/lib/dynamodb/types.js#L26 when

```
import DynamoDBSet from 'aws-sdk/lib/dynamodb/set';

new DynamoDBSet([1, 2]);
```

```
    at isBinary (.../node_modules/aws-sdk/lib/dynamodb/types.js:26:12)
    at typeOf (.../node_modules/aws-sdk/lib/dynamodb/types.js:6:36)
    at Set.detectType (.../node_modules/aws-sdk/lib/dynamodb/set.js:35:37)
    at Set.initialize (.../node_modules/aws-sdk/lib/dynamodb/set.js:28:10)
    at new Set (.../node_modules/aws-sdk/lib/dynamodb/set.js:22:10)
```

I noticed it actually started happening after updating a dev dependency of jest-dynalite that introduced this new dependency @aws/dynamodb-auto-marshaller@^0.7.1

Downgrading jest-dynalite (consequently removes the dependency) it works as expected.

see https://github.com/aws/aws-sdk-js/issues/3601

**Comment by freshollie** [comment]
What version of `aws-sdk` have you got installed in your lockfile when you upgrade to a never version of `jest-dynalite`? I've looked at the code in https://github.com/awslabs/dynamodb-data-mapper-js/tree/master/packages/dynamodb-auto-marshaller and I can't see how this should be causing issues :/.

**Comment by freshollie** [comment]
I think I've found the issue, and answered in the other thread. I'm not 100% sure why upgrading `jest-dynalite` caused this to show. Did you upgrade `aws-sdk` at the same time?

**Comment by freshollie** [comment]
I've put a repro in the other thread. I don't think this has anything to do with jest-dyanlite. I'll reopen if you find out otherwise.

**Comment by onhate** [comment]
ok @freshollie according to your comment on the original issue on aws-sdk repository it makes sense that it's not directly related to jest-dynalite

**Comment by freshollie** [comment]
FYI. The reason this caused an after upgrading is because your code was relying on `aws-sdk` being imported first, which `jest-dynalite` was originally doing (setting up the module cache is such).

From `v3.3.1` jest-dynalite dynamically imports `aws-sdk`, which means it has less side effects on your code and thus highlighted this issue.
